"""FIRST unit tests for changed code only — generated by the unit-test-generator agent.

Covers: BUG-A boundary (is_within_daily_limit), BUG-B empty-sequence guard
(average_transaction), and VULN-1 injection-blocked (export_report).

Does NOT duplicate tests/test_baseline.py.
FIRST compliance per test is noted inline.
"""

from __future__ import annotations

import pytest

from paycli import report
from paycli import transactions as tx


# ---------------------------------------------------------------------------
# BUG-A: is_within_daily_limit uses inclusive upper bound (spent + amount <= limit)
# ---------------------------------------------------------------------------


class TestBugABoundary:
    """Complementary boundary probes not already in test_baseline.py."""

    # Fast / Isolated / Repeatable / Self-validating / Timely — pure arithmetic, no I/O
    def test_zero_base_full_limit_charge_is_allowed(self):
        # spent=0, charge=entire limit → should be allowed (boundary at zero base)
        assert tx.is_within_daily_limit(0.0, 100.0, 100.0) is True

    def test_fractional_boundary_exactly_at_limit_is_allowed(self):
        # 99.99 + 0.01 == 100.0 exactly — tests float representation at boundary
        assert tx.is_within_daily_limit(99.99, 0.01, 100.0) is True

    def test_one_cent_over_limit_is_rejected(self):
        # 99.99 + 0.02 = 100.01 → over the limit
        assert tx.is_within_daily_limit(99.99, 0.02, 100.0) is False

    def test_large_amounts_exact_limit_is_allowed(self):
        assert tx.is_within_daily_limit(9_000.00, 1_000.00, 10_000.00) is True

    def test_large_amounts_one_cent_over_is_rejected(self):
        assert tx.is_within_daily_limit(9_000.00, 1_000.01, 10_000.00) is False

    def test_return_type_is_bool(self):
        result = tx.is_within_daily_limit(50.0, 50.0, 100.0)
        assert isinstance(result, bool)


# ---------------------------------------------------------------------------
# BUG-B: average_transaction returns 0.0 for an empty sequence, no exception
# ---------------------------------------------------------------------------


class TestBugBEmpty:
    """Guard against ZeroDivisionError and verify the correct return value."""

    # baseline already checks [] == 0; these add type safety and edge angles
    def test_empty_does_not_raise(self):
        # Fast/Isolated: pure call, no I/O
        try:
            tx.average_transaction([])
        except ZeroDivisionError:
            pytest.fail("average_transaction([]) raised ZeroDivisionError — BUG-B not fixed")

    def test_empty_returns_float_zero(self):
        # Self-validating: checks exact float identity, not just truthiness
        result = tx.average_transaction([])
        assert result == 0.0
        assert isinstance(result, float)

    def test_single_element_returns_that_element(self):
        # Ensures non-empty path is not broken by the empty guard
        assert tx.average_transaction([42.5]) == 42.5

    def test_negative_values_average(self):
        # Edge case: all negatives should still work
        assert tx.average_transaction([-10.0, -20.0]) == -15.0


# ---------------------------------------------------------------------------
# VULN-1: export_report no longer uses shell=True; injection payload has no effect
# ---------------------------------------------------------------------------


class TestVuln1InjectionBlocked:
    """Verify that a shell-injection payload in the path argument has no side effect."""

    def test_injection_payload_creates_no_side_effect_file(self, tmp_path):
        # FIRST: Isolated via tmp_path; Repeatable (no persistent state)
        side_effect = tmp_path / "injected.txt"
        # Old shell=True code: `cat {path} > report.txt` would execute the `;touch ...` part
        payload = f"nonexistent_file; touch {side_effect}"

        result = report.export_report(payload)

        # New file-I/O code treats the whole string as a filename → OSError → return 1
        assert result == 1, "export_report should return 1 for a bad path"
        assert not side_effect.exists(), (
            "Injection side-effect file was created — VULN-1 is NOT fixed!"
        )

    def test_valid_path_copies_content_correctly(self, tmp_path, monkeypatch):
        # Ensure normal operation still works (regression guard)
        # monkeypatch.chdir isolates the 'report.txt' write to tmp_path
        monkeypatch.chdir(tmp_path)
        src = tmp_path / "input.txt"
        src.write_bytes(b"hello paycli")

        result = report.export_report(str(src))

        assert result == 0
        assert (tmp_path / "report.txt").read_bytes() == b"hello paycli"

    def test_missing_source_path_returns_one(self, tmp_path):
        # OSError branch: file does not exist
        result = report.export_report(str(tmp_path / "does_not_exist.txt"))
        assert result == 1

    def test_no_subprocess_shell_in_source(self):
        # Self-documenting: verify at the source level that shell=True is gone
        import inspect

        source = inspect.getsource(report.export_report)
        assert "shell=True" not in source, "shell=True found in export_report — VULN-1 not fixed!"
        assert "subprocess" not in source, "subprocess call found — injection risk remains"
