"""FIRST unit tests generated by unit-test-generator for bug batch 001.

Covers exactly the three changed behaviours:
  BUG-A  -- is_within_daily_limit inclusive boundary (Change 1, transactions.py)
  BUG-B  -- average_transaction empty-sequence guard (Change 2, transactions.py)
  VULN-1 -- export_report shell-injection payload blocked (Change 4, report.py)

FIRST compliance is noted per test.
"""

from __future__ import annotations


import pytest

from paycli import transactions as tx
from paycli.report import export_report


# ---------------------------------------------------------------------------
# BUG-A: inclusive daily-limit boundary
# ---------------------------------------------------------------------------

def test_bug_a_boundary_exactly_at_limit_is_allowed():
    """BUG-A: spent + amount == limit must return True (inclusive <=).

    FIRST: Fast (pure arithmetic), Independent (no shared state),
    Repeatable (deterministic inputs), Self-validating (assert),
    Timely (written to lock in the fix before this lands in prod).

    Uses inputs (0.0, 50.0, 50.0) -- different from baseline (60,40,100)
    to exercise the zero-spent edge of the boundary.
    """
    result = tx.is_within_daily_limit(spent=0.0, amount=50.0, limit=50.0)
    assert result is True


def test_bug_a_boundary_one_cent_over_limit_is_rejected():
    """BUG-A: spent + amount == limit + 0.01 must return False.

    FIRST: Fast, Independent, Repeatable, Self-validating, Timely.

    Complements the at-limit test; baseline covers (60,41,100) but not
    the minimal overshoot from zero-spent.
    """
    result = tx.is_within_daily_limit(spent=0.0, amount=50.01, limit=50.0)
    assert result is False


# ---------------------------------------------------------------------------
# BUG-B: empty-sequence average guard
# ---------------------------------------------------------------------------

def test_bug_b_average_empty_returns_float_zero():
    """BUG-B: average_transaction([]) must return 0.0 (float), not raise.

    FIRST: Fast, Independent, Repeatable, Self-validating, Timely.

    The baseline checks == 0 (int comparison); this test additionally
    asserts the return type is float to lock in the implementation detail.
    """
    result = tx.average_transaction([])
    assert result == 0.0
    assert isinstance(result, float)


def test_bug_b_average_empty_does_not_raise():
    """BUG-B: calling average_transaction([]) must NOT raise any exception.

    FIRST: Fast, Independent, Repeatable, Self-validating, Timely.

    Uses pytest.raises as a guard: if the call raises, the test fails.
    """
    try:
        tx.average_transaction([])
    except Exception as exc:  # noqa: BLE001
        pytest.fail(f"average_transaction([]) raised unexpectedly: {exc!r}")


# ---------------------------------------------------------------------------
# VULN-1: shell-injection payload must not be executed
# ---------------------------------------------------------------------------

def test_vuln1_injection_payload_does_not_create_side_effect_file(tmp_path, monkeypatch):
    """VULN-1: a shell-injection payload in the path argument must not execute.

    The old code used subprocess.call(..., shell=True), which would interpret
    metacharacters and create the side-effect file. The fix uses shutil.copyfile
    so the payload is treated as a literal (non-existent) path, causing an OSError.

    FIRST: Fast (no network/subprocess), Independent (tmp_path is isolated),
    Repeatable (deterministic; no OS state leak), Self-validating (two asserts),
    Timely (written to prove the vulnerability is closed).

    Asserts:
    1. export_report returns 1 (error code — source path does not exist).
    2. The side-effect file 'pwned' does NOT exist (injection was NOT executed).
    """
    pwned_file = tmp_path / "pwned"
    # Build injection payload targeting tmp_path so even a successful injection
    # would land in an isolated directory rather than /tmp.
    injection_path = f"x; touch {pwned_file}"

    # Run in tmp_path so any accidental report.txt writes are also isolated.
    monkeypatch.chdir(tmp_path)

    return_code = export_report(injection_path)

    assert return_code == 1, (
        "export_report must return 1 when the path does not exist"
    )
    assert not pwned_file.exists(), (
        f"Side-effect file '{pwned_file}' was created — injection was NOT blocked!"
    )


def test_vuln1_benign_path_succeeds(tmp_path, monkeypatch):
    """VULN-1: a benign path still works correctly after the fix.

    Validates that removing shell=True did not break the happy path.

    FIRST: Fast, Independent (tmp_path), Repeatable, Self-validating, Timely.
    """
    src = tmp_path / "input.txt"
    src.write_text("payment data")
    monkeypatch.chdir(tmp_path)

    return_code = export_report(str(src))

    assert return_code == 0
    assert (tmp_path / "report.txt").read_text() == "payment data"
